### ISSUE TITLE
Bambulab hotend support

### ISSUE THREAD

**Issue by 33martin** [Armchair-Heavy-Industries/Xol-Toolhead#16]
Hi team, does Xol support the Bambulab Hotend?  It looks like it is not on the list of supported hotends.

thx

**Comment by BelgarionNL** [comment]
I would also be very happy if a bambulab hotend support could be added.

**Comment by DW-Tas** [comment]
Bambulab mounts available via usermod: https://github.com/Armchair-Heavy-Industries/Armchair-Usermods/tree/main/files/Xol-Toolhead/BambuLab_Xol_HE_Mount

Based off the same CAD building blocks as the release hotend mounts.
