### ISSUE TITLE
Ducts design around M2 bolt holes does not allow enough space for M2 head

### ISSUE THREAD

**Issue by pajtaz** [Armchair-Heavy-Industries/Xol-Toolhead#17]
In ducts design where M2 bolts go through the ducts to attach the fans, there is only 1.5mm of space between center of M2 bolt hole and two walls of the duct. DIN 912 M2 bolt head is minimum 3.62mm and maximum 3.8mm diameter. Several users have reported M2 bolts not fitting and causing splitting of the duct wall.

See attached photo from latest CAD.
![Ducts M2 head](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/19250632/942bf958-0904-4b46-8973-92fed0a53675)

When this is sliced with 100% line width, 0.4mm nozzle, one of the walls ends up with only two perimeters. See attached picture from the slicer preview.
![Slicer preview](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/19250632/6492c038-9025-4601-acd6-1c47ed4117e0)

**Comment by DW-Tas** [comment]
No longer an issue with the release on 2024-06-19. These screws are no longer needed with combined ducts/HE mount design.
