### ISSUE TITLE
Xol HE Mount - NF-Crazy_fanHS.stl feedback

### ISSUE THREAD

**Issue by YesterdaysCoffee** [Armchair-Heavy-Industries/Xol-Toolhead#23]
All these mods I've done on my copy.
1) HS holes for hot-end fan could be 4-6mm deeper, otherwise plastic gets back filled into heat set, deeper holes will also allow for 20mm screws to be pulled snug.

2) The posts for the topmost fan mounts (when sitting on the build plate):  This 'wing' snaps easily, due to a smaller layer area at this point.
A small support web has been added, this web needs to be much larger.  On my copy I will widen the web in to the HE fan platform and out a good 10mm.  Perhaps out to flush with the part fan.

3) The bottom most HS post (oriented on the printer) would benefit by adding webbing to close the gap between main gap and horizontal HS socket.

**Comment by DW-Tas** [comment]
Hi @YesterdaysCoffee, would you mind adding some screenshots to assist with your descriptions?

**Comment by YesterdaysCoffee** [comment]
<img width="667" alt="NF crazy fan mount modifications A" src="https://github.com/Armchair-Engineering/Xol-Toolhead/assets/126969641/1ee10657-34b0-4cb1-96e6-d75b59ca2925">
<img width="839" alt="NF crazy fan mount modifications B" src="https://github.com/Armchair-Engineering/Xol-Toolhead/assets/126969641/10010a22-07bb-4013-84de-d557b7a70ffc">

**Comment by YesterdaysCoffee** [comment]
I am not suggesting the wire channel be moved or the wire splitter mounts be added.

**Comment by DW-Tas** [comment]
1. Hole depth:
These holes are already extended to accept 20mm screws: <br />
![image](https://github.com/Armchair-Engineering/Xol-Toolhead/assets/116466447/eddfffd5-d85a-4acf-916c-a1cb72a3e2ca)
<br/><br/>
2. Top "wings" breaking:
That is standard geometry on all Xol HE mounts and it doesn't have issues with "snapping easily". If it is breaking there for you, I recommend to print hotter and slower to improve layer adhesion.
<br/><br/>
3. Bottom heatset holes:
This is also standard geometry for Xol parts, but as the NF-crazy is a lower hotend than most, I will look to see if this can be done without increasing the toolhead weight. From a quick look, this may be possible withouth changing print perimiter lenght and may provide some bonus stability. Thanks for the idea :)
