### ISSUE TITLE
Xol LED Ducts - Tri-Vane Asym Right - Trident.stl | missing cutout prevents LED from beeing installed

### ISSUE THREAD

**Issue by shnizzl** [Armchair-Heavy-Industries/Xol-Toolhead#34]
Hello, it seems there is a missing cutout/extrusion in the file _Xol LED Ducts - Tri-Vane Asym Right - Trident.stl_, which makes it impossible to install Neopixel LED with soldered on wires. The LED without wires does fit in die printed part, but anything that is soldered on would be sheared off while pushing the LED into its slot: 
![issue0](https://github.com/Armchair-Heavy-Industries/Xol-Toolhead/assets/122225066/4e2e3f0e-1882-4a2b-842b-c3b800857945)
![issue1](https://github.com/Armchair-Heavy-Industries/Xol-Toolhead/assets/122225066/e312cb4c-77db-4aa3-bdab-b819fd9747c0)
This only affects _Xol LED Ducts - Tri-Vane Asym Right - **Trident**.stl_, both _Xol LED Ducts - Tri-Vane Asym **Left**.stl_ and _Xol LED Ducts - Tri-Vane Asym **Right**.stl_ are fine.

**Comment by DW-Tas** [comment]
Thanks @shnizzl .  Updated STLS and STEP files have been uploaded.
