### ISSUE TITLE
BTT Eddy (Beacon Clone) Support in planing?

### ISSUE THREAD

**Issue by toscdesign** [Armchair-Heavy-Industries/Xol-Toolhead#37]
Hi,
there ist a new Probe available.
The Bigtreetech Eddy.

This is a Beacon Clone with integrated Raspberry Pico and USB Connection:
https://github.com/bigtreetech/Eddy

It would bei nice to use it with the XOL Toolhead.
I have ordered one and would make myself available as a beta tester if needed.

**Comment by DW-Tas** [comment]
So Xol isn't likely to support Eddie. There is a collision between Eddie and the X rail carriage. 
![image](https://github.com/Armchair-Heavy-Industries/Xol-Toolhead/assets/116466447/a868d00a-db8b-4259-89a4-72e7c1a19b55)

**Comment by toscdesign** [comment]
Ah ok, thanks for the picture!

Is this the normal XOL or the longer Version for a Rapido UHF?
The long Version could have enough space, but I'm not sure.

Do we need the case from the Eddy?
As far as I know, it ist possible to use the pcb of the Eddy without it. The pcb itself hast mountingholes for screws.

This could be a way to use the Eddy with XOL

**Comment by DW-Tas** [comment]
The PCB holes are in the same spot, and there is a JST connector at the top (in the gap shown in the picture). It would probably work with the UHF versions, but I am not going to make something that won't work with all versions.
The CAD for the existing probe modules is available if someone wants to make a UHF only usermod.
