### ISSUE TITLE
experimental cpap difference between UHF duct and non UHF

### ISSUE THREAD

**Issue by Dario-Ciceri** [Armchair-Heavy-Industries/Xol-Toolhead#39]
Hi, I checked the two models but I don't see any difference, is UHF a placeholder for the uhf version or does it refer to something else?
thanks

**Comment by DW-Tas** [comment]
Hi. did you put them side by side in a slicer? 
![image](https://github.com/Armchair-Heavy-Industries/Xol-Toolhead/assets/116466447/e0af2228-b608-4c21-811e-67726975a990)

**Comment by Dario-Ciceri** [comment]
> Hi. did you put them side by side in a slicer? ![image](https://private-user-images.githubusercontent.com/116466447/337875792-e0af2228-b608-4c21-811e-67726975a990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTI0MTEsIm5iZiI6MTcxNzg1MjExMSwicGF0aCI6Ii8xMTY0NjY0NDcvMzM3ODc1NzkyLWUwYWYyMjI4LWI2MDgtNGMyMS04MTFlLTY3NzI2OTc1YTk5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMzA4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGMzZmYxZTA0YmVkN2M2MGZkYzM4Y2MzYWFjNTFlZWRkZDgwMjgxNDQxMTg0NDI0NjYzNjU0MDEyMjlkMTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4k5txKdG6OgbrTjGEK3hOMiyM7Ds4vGtyuLxpb7lMnU)

damn I didn't as I was using CAD and didn't notice... sorry...
