### ISSUE TITLE
Add a filament cutting feature

### ISSUE THREAD

**Issue by Kaympe20** [Armchair-Heavy-Industries/Xol-Toolhead#40]
Is there a way to add compatibility for a filament cutter similar to that of [Filametrix](https://github.com/sorted01/Filametrix)? I would like to use the Xol-Toolhead, but I use the Enraged Rabbit Carrot Feeder.

**Comment by DW-Tas** [comment]
Have a look at Xol-metrix mod by SouthAsh1. They even have some based on the new release already under the BETA STLs

https://github.com/SouthAsh1/Xol-metrix

https://github.com/SouthAsh1/Xol-metrix/tree/main/STL/BETA
