### ISSUE TITLE
EBB SB2209 CAN support?

### ISSUE THREAD

**Issue by tonieMajke** [Armchair-Heavy-Industries/Xol-Toolhead#45]
Are there plans to support SB2209 can?

**Comment by DW-Tas** [comment]
No, The SB2209 is designed specifically for StealthBurner only.
There is a usermod for an older board that the SB2209 form factor is based on that may work: https://github.com/Armchair-Heavy-Industries/Armchair-Usermods/tree/main/files/Xol-Toolhead/Afterburner_Toolhead_PCB_Mount
