### ISSUE TITLE
Rapido ACE UHF

### ISSUE THREAD

**Issue by Sotiocsi** [Armchair-Heavy-Industries/Xol-Toolhead#51]
Hi!

Could I have a "Xol_HE_mount_fan" for Rapido ACE UHF step format?

Rapido ACE UHF is exactly 3 mm shorter than rapido UHF.

THX.

**Comment by DW-Tas** [comment]
Doesn't the Rapido ACE come with a 3mm spacer for that reason?

**Comment by Sotiocsi** [comment]
but, yes. I wanted to leave it out to make it as short as possible.

**Comment by Sotiocsi** [comment]
i see "Xol_HE_Mount-Dragon-Ace_Extender_Fan" is good for rapido ace UHF.
