### ISSUE TITLE
Request: Third Cooling fan - Voron TAP

### ISSUE THREAD

**Issue by JesNoFear** [Armchair-Heavy-Industries/Xol-Toolhead#55]
Concept is to have a third cooling fan to cool the backside of the toolhead. Sadly I lack Fusion / CAD skills to make this, which is why i am asking :-)

I found this (linked) third cooling fan for SB + Voron TAP (Chaoticlabs CNC Voron TAP), which works well. but I would like it to be more uniform with the XOL setup.
https://www.teamfdm.com/files/file/738-stealth-burner-3rd-parts-cooling-fan-mount/

Concept image (I frenkenstined this together)
![image](https://github.com/user-attachments/assets/3f42ac1a-79dd-4982-8304-4abef5629188)

I am thinking to make this work / make it better for the XOL would be to reverse the fan insert direction, instead of inserting the opening, inserting the closed side from the top so the duct can be part of the print / permanently attached unlike in my example.

with the 3010 fan its small enough to not extend past the clearance of the 2020 extrusion, making it a no adjustment add-on.

GDSTime makes a 24v 3010 blower that seems to be working well so far.
![image](https://github.com/user-attachments/assets/be714c27-c107-4d44-8be0-7d2a10b2e45d)

I have tinkered around with trying to fit a 4010 blower back there, but it doesn't offer enough clearance, even at an angle to compensate for the extra length, TAP loses its full motion causing the bracket to snap.

Here is an example of the third fan "as is" without the addition of a duct.
![IMG_20241129_204920651(1)](https://github.com/user-attachments/assets/178e3fa4-7eee-469d-8af3-41fd7b9852d7)

**Comment by DW-Tas** [comment]
I appreciate you have taken the time to make this request, but it's not something that will be implemented into Xol. This is really a mod for CNC Tap that would not work with Xol-Carriage at all. 

I also expect that a duct like your example with an 'S' bend in the airflow would be less effective than the simple deflector that is already in place.

I would, however, highly recommend that you use this as a reason to learn some CAD skills of your own. It's much easier to learn when you have a good source of motivation.
